### ISSUE TITLE
No Login

### ISSUE THREAD

**Issue by AceHeike** [PhantomPainX/animemac-ionic#1]
Error when trying to login app (v.1.4.3), on the web it works fine.

**Comment by PhantomPainX** [comment]
Hey, can you be more specific please?

The issue happens in normal, biometric or Google login?

**Comment by AceHeike** [comment]
The problem occurred when I attempted to access my account using either the registration email or the Google login (which are linked to the same user). I received an error message stating something like 'Incorrect credentials.' With the previous version, I could use either of these methods to log in without any issues. I also want to mention that I don't encounter these problems on the website. I double-checked before sending this message, and it seems that the Google login option, which didn't work for me previously, is now functioning correctly (??). However, the rest has not changed.

I have already been able to enter (With Google), so it is no longer such a "big" problem.

**Comment by PhantomPainX** [comment]
Did you register your account using the Google button or the formulary?

I'm asking because if you only used the Google button, you can't login using the email and password (bcs the password is not even set)

Anyways if that's the case, you can set a password using the recovery button.

About the Google button, it was an error in my end, so thanks for reporting it 😁

**Comment by PhantomPainX** [comment]
I'm closing this issue.
